CREATE TABLE usuario (
	login varchar(255) NOT NULL,
	email varchar(255),
	nome varchar(255),
	senha varchar(255),
	pontos integer,
	CONSTRAINT usuario_pkey PRIMARY KEY (login)
);

CREATE TABLE topico
(
  id_topico integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1),
  titulo VARCHAR(255),
  conteudo VARCHAR(255),
  login VARCHAR(255),
  CONSTRAINT topico_pkey PRIMARY KEY (id_topico),
  CONSTRAINT topico_login_fkey FOREIGN KEY (login)
      REFERENCES usuario (login) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE comentario
(
  id_comentario integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1),
  comentario VARCHAR(255),
  login VARCHAR(255),
  id_topico integer,
  CONSTRAINT comentario_pkey PRIMARY KEY (id_comentario),
  CONSTRAINT comentario_id_topico_fkey FOREIGN KEY (id_topico)
      REFERENCES topico (id_topico) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT comentario_login_fkey FOREIGN KEY (login)
      REFERENCES usuario (login) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
)